spring:
  redis:
    ##集群
#    cluster:
#      nodes:
#        - 172.21.0.211:7000
#        - 172.21.0.211:7001
#        - 172.21.0.211:7002
#        - 172.21.0.211:7003
#        - 172.21.0.211:7004
    ##哨兵
#    sentinel:
#      master: mymaster
#      nodes:
#        - 172.21.0.211:7005
#        - 172.21.0.211:7006
#        - 172.21.0.211:7007
    ####单机
    database: 0
    host: 192.168.187.212
    password:
    port: 6379
    timeout: 0
    ####连接池
    pool:
      max-active: 100 #连接池最大连接数（使用负值表示没有限制）
      max-wait: 1000  #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 100 #连接池中的最大空闲连接
      min-idle: 0   #连接池中的最小空闲连接
