server:
  port: 8084

spring:
  application:
    name: hystrix-a
  cloud:
      config:
        name: datasource
        discovery:
          enabled: true
          service-id: config-server   #config名称
        profile: default

feign:
  hystrix:
    enabled: true

eureka:
  instance:
      # 使用 ip 代替实例名
      prefer-ip-address: true
      # 实例的主机名
      hostname: ${spring.cloud.client.ip-address}
      # 实例的 ID 规则
      instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
