server:
    port: 9000

spring:
    application:
        name: ribbon-consumer

    freemarker:
        suffix: .html

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka
